// A single column of numbers from the input, plus the options from its header.

import { type Color, getColorByName } from "./colors.js";

export enum SeriesType {
    Left,
    Right,
    Domain,
}

export class Series {
    // The data points. Shrinks by one for each derivative taken.
    private data: number[] = [];

    // What the series should be called, or undefined if not set.
    title: string | undefined = undefined;
    // Color used to draw this series. Filled in by the renderer if not set.
    color: Color | undefined = undefined;
    // Whether to hide this series (omit it from the plot).
    hide = false;
    // Whether to associate the series with the left or right axis, or the domain.
    seriesType: SeriesType = SeriesType.Left;
    // How many derivatives to take of the raw data.
    derivative = 0;
    // Whether to draw this as a log plot. Data must be positive.
    log = false;
    // Whether this represents a year. Causes the number to be drawn without a
    // comma ("2018" instead of "2,018").
    date = false;
    // Whether to always include zero when auto-ranging vertically.
    zero = false;
    // Whether the data was generated by us. For the domain only, when it wasn't
    // specified explicitly in the input.
    isImplicit = false;

    // Minimum value of the points.
    minValue = 0;
    // Maximum value of the points.
    maxValue = 0;
    // Max minus min.
    range = 0;

    static copyOf(other: Series): Series {
        const series = new Series();

        series.data = other.data.slice();
        series.title = other.title;
        series.color = other.color;
        series.hide = other.hide;
        series.seriesType = other.seriesType;
        series.derivative = other.derivative;
        series.log = other.log;
        series.date = other.date;
        series.zero = other.zero;
        series.isImplicit = other.isImplicit;
        series.minValue = other.minValue;
        series.maxValue = other.maxValue;
        series.range = other.range;

        return series;
    }

    // The number of data points.
    get count(): number {
        return this.data.length;
    }

    // Set various data from the header (e.g., "errors [right,red]").
    setHeader(header: string): void {
        const bracket = header.indexOf("[");

        const title = (bracket === -1 ? header : header.substring(0, bracket)).trim();
        this.title = title.length > 0 ? title : undefined;

        if (bracket === -1) {
            return;
        }

        // Options are comma-separated, up to an optional closing bracket.
        for (const rawOption of header.substring(bracket + 1).split(/[,\]]/)) {
            const option = rawOption.trim().toLowerCase();
            if (option.length === 0) {
                continue;
            }

            const color = getColorByName(option);
            if (color !== undefined) {
                this.color = color;
            } else if (option === "hide") {
                this.hide = true;
            } else if (option === "left") {
                this.seriesType = SeriesType.Left;
            } else if (option === "right") {
                this.seriesType = SeriesType.Right;
            } else if (option === "domain") {
                this.seriesType = SeriesType.Domain;
            } else if (option === "derivative") {
                this.derivative += 1;
            } else if (option === "log") {
                this.log = true;
            } else if (option === "date") {
                this.date = true;
            } else if (option === "zero") {
                this.zero = true;
            } else {
                console.warn(`Unknown header option: ${option}`);
            }
        }
    }

    // Add another data point to the series.
    addDataPoint(value: number): void {
        this.data.push(value);
    }

    // Process the data after all data points have been added.
    processData(): void {
        this.computeStats();
    }

    // Return the value at an index.
    valueAt(index: number): number {
        return this.data[index]!;
    }

    private computeStats(): void {
        this.minValue = 0;
        this.maxValue = 0;

        for (let i = 0; i < this.data.length; i++) {
            const value = this.data[i]!;

            if (i === 0 && !this.zero) {
                this.minValue = value;
                this.maxValue = value;
            } else {
                if (value < this.minValue) {
                    this.minValue = value;
                }
                if (value > this.maxValue) {
                    this.maxValue = value;
                }
            }
        }

        this.range = this.maxValue - this.minValue;
    }

    // Replace each point with the average of it and the next point, reducing the
    // number of points by one. Does not update the stats. This is for computing
    // the domains of derivative series.
    replaceWithMidpoints(): void {
        if (this.data.length === 0) {
            return;
        }

        for (let i = 0; i < this.data.length - 1; i++) {
            this.data[i] = (this.data[i]! + this.data[i + 1]!)/2;
        }

        this.data.pop();
    }

    // Convert the series to its derivative with respect to the given domain.
    computeDerivativeWithDomain(domainSeries: Series): void {
        if (this.data.length > 0) {
            for (let i = 0; i < this.data.length - 1; i++) {
                const dx = domainSeries.valueAt(i + 1) - domainSeries.valueAt(i);
                this.data[i] = dx === 0 ? 0 : (this.data[i + 1]! - this.data[i]!)/dx;
            }

            this.data.pop();

            if (this.title !== undefined) {
                this.title += "’";
            }
        }

        this.computeStats();
    }
}
