name: Xcode - Build and Analyze

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          xcodebuild clean build analyze CONFIGURATION_BUILD_DIR=build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -scheme Plotter -project Plotter.xcodeproj
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Plotter
          path: build/Plotter.app
